# src/ai_edms_assistant/application/ports/vector_store_port.py
from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any
from uuid import UUID

from pydantic import BaseModel, Field


class DocumentChunk(BaseModel):
    """Single chunk of text with metadata for vector store ingestion.

    Represents a semantically coherent fragment of a document after chunking.
    Stored in the vector database alongside its embedding vector.

    Attributes:
        text: The chunk text content.
        metadata: Arbitrary key-value metadata (document_id, page, source, etc.).
        chunk_id: Unique identifier for this chunk. Generated by the chunker.
    """

    text: str
    metadata: dict[str, Any] = Field(default_factory=dict)
    chunk_id: str | None = None


class SearchResult(BaseModel):
    """Single result from a vector similarity search.

    Attributes:
        text: The matched chunk text.
        score: Similarity score in [0.0, 1.0]. Higher = more similar.
        metadata: Metadata carried from the original chunk.
        chunk_id: ID of the matched chunk.
    """

    text: str
    score: float
    metadata: dict[str, Any] = Field(default_factory=dict)
    chunk_id: str | None = None


class AbstractVectorStore(ABC):
    """Port (interface) for vector similarity search backends.

    Defines the contract between the application layer and vector store
    infrastructure (Chroma, Pinecone, Qdrant). Used by RAG chains and
    document analysis tools.

    Implementations:
        - ``ChromaVectorStore`` (dev / local)
        - ``PineconeVectorStore`` (prod / cloud)

    Architecture:
        - Application layer receives ``AbstractVectorStore`` via DI.
        - Infrastructure provides concrete stores implementing this interface.
        - Switch stores by changing DI config — no application code change.

    Example:
        >>> # In a RAG use case
        >>> class DocumentSearchUseCase:
        ...     def __init__(self, store: AbstractVectorStore) -> None:
        ...         self._store = store
        ...
        ...     async def execute(self, query: str) -> list[SearchResult]:
        ...         return await self._store.search(query, top_k=5)
    """

    @abstractmethod
    async def add_documents(
        self,
        chunks: list[DocumentChunk],
        collection_name: str = "default",
    ) -> None:
        """Add document chunks to the vector store.

        Embeddings are generated automatically by the store's configured
        embedding model (passed at initialization).

        Args:
            chunks: List of ``DocumentChunk`` objects to ingest.
            collection_name: Collection / index name. Defaults to ``"default"``.
        """

    @abstractmethod
    async def search(
        self,
        query: str,
        top_k: int = 5,
        collection_name: str = "default",
        filter_metadata: dict[str, Any] | None = None,
    ) -> list[SearchResult]:
        """Perform semantic similarity search.

        Args:
            query: Natural-language search query.
            top_k: Number of results to return. Default 5.
            collection_name: Collection / index to search.
            filter_metadata: Optional metadata filters (e.g.
                ``{"document_id": "abc-123"}`` to restrict to one document).

        Returns:
            List of ``SearchResult`` ordered by descending similarity score.
        """

    @abstractmethod
    async def delete_by_document_id(
        self,
        document_id: UUID,
        collection_name: str = "default",
    ) -> None:
        """Delete all chunks associated with a specific document.

        Used when a document is deleted or re-indexed.

        Args:
            document_id: UUID of the document whose chunks to delete.
            collection_name: Collection / index name.
        """

    @abstractmethod
    async def clear_collection(self, collection_name: str = "default") -> None:
        """Delete all chunks in a collection.

        Used for re-indexing workflows or testing.

        Args:
            collection_name: Collection / index name.
        """

    @property
    @abstractmethod
    def backend_name(self) -> str:
        """Returns the name of the vector store backend.

        Returns:
            Backend identifier, e.g. ``"chroma"``, ``"pinecone"``.
        """
